apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - AWS/EKS/airflow-eks-config/charts/airflow-dev-values.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=my-values.yaml