kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: aws-efs
provisioner: aws.io/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: efs-storage-claim
    namespace: dev
    annotations:  
        volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 512Mi