apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    component: webserver
    release: airflow-dev